# Panda Profiling and Feature Engineering

## Import Library Pandas

In [8]:
import pandas as pd

# Import Datasets: Titanic

In [9]:
df = pd.read_csv('train.csv')

In [10]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Pandas Profiling

In [3]:
!pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /Users/arjan/env/lib/python3.8/site-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (2.0.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (3.7.5)
Requirement already satisfied: pydantic>=2 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (2.10.6)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /Users/arjan/env/lib/python3.8/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.24.4)
Requirement already satisfied: htmlmin==0.1.12 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.10)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.14.1)
Requirement already satisfied: typeguard<5,>=3 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (4.4.0)
Requirement already satisfied: imagehash==4.3.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.58.1)
Requirement already satisfied: PyWavelets in /Users/arjan/env/lib/python3.8/site-packages (from imagehash==4.3.1->ydata-profiling) (1.4.1)
Requirement already satisfied: pillow in /Users/arjan/env/lib/python3.8/site-packages (from imagehash==4.3.1->ydata-profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/arjan/env/lib/python3.8/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (6.4.5)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /Users/arjan/env/lib/python3.8/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.41.1)
Requirement already satisfied: importlib-metadata in /Users/arjan/env/lib/python3.8/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (8.5.0)
Requirement already satisfied: pytz>=2020.1 in /Users/arjan/env/lib/python3.8/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/arjan/env/lib/python3.8/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /Users/arjan/env/lib/python3.8/site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/arjan/env/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /Users/arjan/env/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /Users/arjan/env/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.8.3)
Requirement already satisfied: patsy>=0.5.4 in /Users/arjan/env/lib/python3.8/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /Users/arjan/env/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /Users/arjan/env/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.1)
Requirement already satisfied: puremagic in /Users/arjan/env/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: zipp>=3.20 in /Users/arjan/env/lib/python3.8/site-packages (from importlib-metadata->numba<=0.61,>=0.56.0->ydata-profiling) (3.21.0)
Requirement already satisfied: six>=1.5 in /Users/arjan/env/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)

# Import Profile Report

In [11]:
from ydata_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output.html')

Summarize dataset:  18%|█▌       | 3/17 [00:00<00:01, 10.66it/s, Describe variable: SibSp]
Summarize dataset:  65%|███▏ | 11/17 [00:00<00:00, 18.79it/s, Describe variable: Embarked]
100%|█████████████████████████████████████████████████████| 12/12 [00:00<00:00, 48.50it/s]
Summarize dataset: 100%|███████████████████████| 47/47 [00:13<00:00,  3.59it/s, Completed]
Generate report structure: 100%|████████████████████████████| 1/1 [00:15<00:00, 15.28s/it]
Render HTML: 100%|██████████████████████████████████████████| 1/1 [00:02<00:00,  2.55s/it]
Export report to file: 100%|████████████████████████████████| 1/1 [00:00<00:00, 47.57it/s]

# Import Datasets: Hotel

In [12]:
hotel = pd.read_csv('hotel.csv')

In [13]:
hotel

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

## Now Pandas Profiling of Hotel.CSV Data

In [14]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /Users/arjan/env/lib/python3.8/site-packages (4.16.1)
Requirement already satisfied: scipy<1.16,>=1.4.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (2.0.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (3.7.5)
Requirement already satisfied: pydantic>=2 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (2.10.6)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /Users/arjan/env/lib/python3.8/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.24.4)
Requirement already satisfied: htmlmin==0.1.12 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.12.4)
Requirement already satisfied: requests<3,>=2.24.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.10)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.14.1)
Requirement already satisfied: typeguard<5,>=3 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (4.4.0)
Requirement already satisfied: imagehash==4.3.1 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.3 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.9.4)
Requirement already satisfied: dacite>=1.8 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /Users/arjan/env/lib/python3.8/site-packages (from ydata-profiling) (0.58.1)
Requirement already satisfied: PyWavelets in /Users/arjan/env/lib/python3.8/site-packages (from imagehash==4.3.1->ydata-profiling) (1.4.1)
Requirement already satisfied: pillow in /Users/arjan/env/lib/python3.8/site-packages (from imagehash==4.3.1->ydata-profiling) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/arjan/env/lib/python3.8/site-packages (from jinja2<3.2,>=2.11.1->ydata-profiling) (2.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/arjan/env/lib/python3.8/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (6.4.5)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /Users/arjan/env/lib/python3.8/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (0.41.1)
Requirement already satisfied: importlib-metadata in /Users/arjan/env/lib/python3.8/site-packages (from numba<=0.61,>=0.56.0->ydata-profiling) (8.5.0)
Requirement already satisfied: pytz>=2020.1 in /Users/arjan/env/lib/python3.8/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/arjan/env/lib/python3.8/site-packages (from pandas!=1.4.0,<3.0,>1.1->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /Users/arjan/env/lib/python3.8/site-packages (from phik<0.13,>=0.11.1->ydata-profiling) (1.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/arjan/env/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /Users/arjan/env/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /Users/arjan/env/lib/python3.8/site-packages (from pydantic>=2->ydata-profiling) (4.12.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/arjan/env/lib/python3.8/site-packages (from requests<3,>=2.24.0->ydata-profiling) (2025.8.3)
Requirement already satisfied: patsy>=0.5.4 in /Users/arjan/env/lib/python3.8/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /Users/arjan/env/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /Users/arjan/env/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.1)
Requirement already satisfied: puremagic in /Users/arjan/env/lib/python3.8/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (1.30)
Requirement already satisfied: zipp>=3.20 in /Users/arjan/env/lib/python3.8/site-packages (from importlib-metadata->numba<=0.61,>=0.56.0->ydata-profiling) (3.21.0)
Requirement already satisfied: six>=1.5 in /Users/arjan/env/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from ydata_profiling import ProfileReport
prof = ProfileReport(hotel)
prof.to_file(output_file = 'output-hotel.html')

Summarize dataset:   0%|     | 0/37 [00:00<?, ?it/s, Describe variable: arrival_date_year]
Summarize dataset:  16%|█▎      | 6/37 [00:04<00:13,  2.29it/s, Describe variable: adults]
%|█▋                                                    | 1/32 [00:03<01:36,  3.12s/it]
%|███▍                                                  | 2/32 [00:03<00:42,  1.42s/it]
Summarize dataset:  27%|█▌    | 10/37 [00:05<00:13,  2.04it/s, Describe variable: country]
Summarize dataset:  30%|█▊    | 11/37 [00:06<00:11,  2.29it/s, Describe variable: country]
Summarize dataset:  30%|▎| 11/37 [00:06<00:11,  2.29it/s, Describe variable: market_segmen
%|███████████▊                                          | 7/32 [00:05<00:13,  1.84it/s]
%|█████████████▌                                        | 8/32 [00:05<00:10,  2.30it/s]
Summarize dataset:  32%|▎| 12/37 [00:07<00:14,  1.77it/s, Describe variable: market_segmen
Summarize dataset:  35%|▎| 13/37 [00:07<00:11,  2.08it/s, Describe variable: distribution_
Summarize dataset:  35%|▎| 13/37 [00:07<00:11,  2.08it/s, Describe variable: is_repeated_g
Summarize dataset:  41%|▍| 15/37 [00:07<00:09,  2.38it/s, Describe variable: is_repeated_g
Summarize dataset:  43%|▍| 16/37 [00:08<00:08,  2.34it/s, Describe variable: reserved_room
Summarize dataset:  46%|▍| 17/37 [00:08<00:07,  2.53it/s, Describe variable: reserved_room
Summarize dataset:  51%|▌| 19/37 [00:08<00:04,  3.96it/s, Describe variable: booking_chang
Summarize dataset:  51%|▌| 19/37 [00:08<00:04,  3.96it/s, Describe variable: deposit_type]
%|████████████████████████████▏                        | 17/32 [00:08<00:03,  4.00it/s]
Summarize dataset:  59%|▌| 22/37 [00:10<00:06,  2.26it/s, Describe variable: days_in_waiti
Summarize dataset:  62%|▌| 23/37 [00:10<00:05,  2.63it/s, Describe variable: days_in_waiti
Summarize dataset:  70%|▋| 26/37 [00:10<00:02,  4.48it/s, Describe variable: total_of_spec
%|███████████████████████████████████████▊             | 24/32 [00:09<00:01,  5.26it/s]
%|█████████████████████████████████████████▍           | 25/32 [00:09<00:01,  5.63it/s]
Summarize dataset:  81%|▊| 30/37 [00:12<00:02,  2.68it/s, Describe variable: reservation_s
Summarize dataset:  84%|▊| 31/37 [00:12<00:02,  2.49it/s, Describe variable: reservation_s
Summarize dataset:  86%|▊| 32/37 [00:13<00:01,  2.80it/s, Describe variable: reservation_s
100%|█████████████████████████████████████████████████████| 32/32 [00:12<00:00,  2.60it/s]
Summarize dataset: 100%|█████████████████████| 238/238 [01:59<00:00,  1.99it/s, Completed]
Generate report structure: 100%|████████████████████████████| 1/1 [00:29<00:00, 29.93s/it]
Render HTML: 100%|██████████████████████████████████████████| 1/1 [00:13<00:00, 13.10s/it]
Export report to file: 100%|████████████████████████████████| 1/1 [00:00<00:00, 20.16it/s]